package com.example.cocktailsproject.models

import com.squareup.moshi.Json

data class Drinks(
    @Json(name = "idDrink") var idDrink: String? = null,
    @Json(name = "strDrink") var strDrink: String? = null,
    @Json(name = "strDrinkAlternate") var strDrinkAlternate: String? = null,
    @Json(name = "strTags") var strTags: String? = null,
    @Json(name = "strVideo") var strVideo: String? = null,
    @Json(name = "strCategory") var strCategory: String? = null,
    @Json(name = "strIBA") var strIBA: String? = null,
    @Json(name = "strAlcoholic") var strAlcoholic: String? = null,
    @Json(name = "strGlass") var strGlass: String? = null,
    @Json(name = "strInstructions") var strInstructions: String? = null,
    @Json(name = "strInstructionsES") var strInstructionsES: String? = null,
    @Json(name = "strInstructionsDE") var strInstructionsDE: String? = null,
    @Json(name = "strInstructionsFR") var strInstructionsFR: String? = null,
    @Json(name = "strInstructionsIT") var strInstructionsIT: String? = null,
    @Json(name = "strInstructionsZH-HANS") var strInstructionsZHHANS: String? = null,
    @Json(name = "strInstructionsZH-HANT") var strInstructionsZHHANT: String? = null,
    @Json(name = "strDrinkThumb") var strDrinkThumb: String? = null,
    @Json(name = "strIngredient1") var strIngredient1: String? = null,
    @Json(name = "strIngredient2") var strIngredient2: String? = null,
    @Json(name = "strIngredient3") var strIngredient3: String? = null,
    @Json(name = "strIngredient4") var strIngredient4: String? = null,
    @Json(name = "strIngredient5") var strIngredient5: String? = null,
    @Json(name = "strIngredient6") var strIngredient6: String? = null,
    @Json(name = "strIngredient7") var strIngredient7: String? = null,
    @Json(name = "strIngredient8") var strIngredient8: String? = null,
    @Json(name = "strIngredient9") var strIngredient9: String? = null,
    @Json(name = "strIngredient10") var strIngredient10: String? = null,
    @Json(name = "strIngredient11") var strIngredient11: String? = null,
    @Json(name = "strIngredient12") var strIngredient12: String? = null,
    @Json(name = "strIngredient13") var strIngredient13: String? = null,
    @Json(name = "strIngredient14") var strIngredient14: String? = null,
    @Json(name = "strIngredient15") var strIngredient15: String? = null,
    @Json(name = "strMeasure1") var strMeasure1: String? = null,
    @Json(name = "strMeasure2") var strMeasure2: String? = null,
    @Json(name = "strMeasure3") var strMeasure3: String? = null,
    @Json(name = "strMeasure4") var strMeasure4: String? = null,
    @Json(name = "strMeasure5") var strMeasure5: String? = null,
    @Json(name = "strMeasure6") var strMeasure6: String? = null,
    @Json(name = "strMeasure7") var strMeasure7: String? = null,
    @Json(name = "strMeasure8") var strMeasure8: String? = null,
    @Json(name = "strMeasure9") var strMeasure9: String? = null,
    @Json(name = "strMeasure10") var strMeasure10: String? = null,
    @Json(name = "strMeasure11") var strMeasure11: String? = null,
    @Json(name = "strMeasure12") var strMeasure12: String? = null,
    @Json(name = "strMeasure13") var strMeasure13: String? = null,
    @Json(name = "strMeasure14") var strMeasure14: String? = null,
    @Json(name = "strMeasure15") var strMeasure15: String? = null,
    @Json(name = "strImageSource") var strImageSource: String? = null,
    @Json(name = "strImageAttribution") var strImageAttribution: String? = null,
    @Json(name = "strCreativeCommonsConfirmed") var strCreativeCommonsConfirmed: String? = null,
    @Json(name = "dateModified") var dateModified: String? = null
)
